package com.example.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.compositionLocalOf
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue

enum class AppLanguage(val code: String, val displayName: String) {
    EN("en", "English"),
    RU("ru", "Русский"),
    KY("ky", "Кыргызча")
}

enum class TextKey {
    APP_NAME,
    TAGLINE,
    SPLASH_SUBTITLE,
    GET_STARTED,
    ONBOARDING_TITLE_1,
    ONBOARDING_DESC_1,
    ONBOARDING_TITLE_2,
    ONBOARDING_DESC_2,
    ONBOARDING_TITLE_3,
    ONBOARDING_DESC_3,
    NEXT,
    SKIP,
    AUTH_TITLE,
    AUTH_SUBTITLE,
    AUTH_GOOGLE_BTN,
    AUTH_AGREE,
    SEARCH_PLACEHOLDER,
    SECTION_RECOMMENDATIONS,
    SECTION_NEARBY,
    SETTINGS_TITLE,
    SETTINGS_LANG,
    SETTINGS_THEME,
    SETTINGS_NOTIFICATIONS,
    SETTINGS_PRIVACY,
    SETTINGS_ACCOUNT,
    SETTINGS_SAVE,
    PROFILE_TITLE,
    PROFILE_BIO,
    PROFILE_EDIT,
    PROFILE_VERIFIED,
    PROFILE_PREFS,
    ASSISTANT_TITLE,
    ASSISTANT_PLACEHOLDER,
    GROUP_JOIN,
    GROUP_LEAVE,
    GROUP_CHAT,
    GROUP_MEMBERS,
    GROUP_MEETING,
    WEATHER_HOT_ALERT,
    WEATHER_RAIN_ALERT,
    WEATHER_GOOD_ALERT,
    SAFETY_REPORT,
    SAFETY_REPORT_SUBMITTED,
    INTENT_PROMPT_LABEL,
    DISCOVER_MATCHES_TITLE,
    GO_BACK,
    NAV_HOME,
    NAV_ASSISTANT,
    NAV_PROFILE,
    NAV_SETTINGS,
    NAV_MAP,
    BUDGET_FREE,
    BUDGET_CHEAP,
    BUDGET_MEDIUM,
    BUDGET_EXPENSIVE,
    TIME_NOW,
    TIME_TODAY,
    TIME_TONIGHT,
    TIME_WEEKEND,
    CATEGORY_SPORTS,
    CATEGORY_GAMES,
    CATEGORY_OUTDOORS,
    CATEGORY_SOCIAL,
    CATEGORY_MUSIC
}

object LanguageManager {
    private val translations = mapOf(
        AppLanguage.EN to mapOf(
            TextKey.APP_NAME to "Meetly",
            TextKey.TAGLINE to "Meet people. Do things.",
            TextKey.SPLASH_SUBTITLE to "Google Search for real-life activities",
            TextKey.GET_STARTED to "Get Started",
            TextKey.ONBOARDING_TITLE_1 to "Intention First",
            TextKey.ONBOARDING_DESC_1 to "No endless profile scrolling. Just say what you want to do, and Meetly finds your people immediately.",
            TextKey.ONBOARDING_TITLE_2 to "Smart AI Grouping",
            TextKey.ONBOARDING_DESC_2 to "Our AI matching engine clubs similar intentions, maps venues, suggests times, and creates ephemeral chat groups.",
            TextKey.ONBOARDING_TITLE_3 to "Turn Intent into Action",
            TextKey.ONBOARDING_DESC_3 to "Football, volleyball, nature walks, picnics, or board games. Turn plans into immediate real-life action.",
            TextKey.NEXT to "Next",
            TextKey.SKIP to "Skip",
            TextKey.AUTH_TITLE to "Join Meetly Today",
            TextKey.AUTH_SUBTITLE to "Find your sunset activity buddies or casual fun coordinates.",
            TextKey.AUTH_GOOGLE_BTN to "Continue with Google",
            TextKey.AUTH_AGREE to "By continuing, you agree with our verified safety standard regulations.",
            TextKey.SEARCH_PLACEHOLDER to "What do you want to do? (e.g., 'volley in 1 hr')",
            TextKey.SECTION_RECOMMENDATIONS to "AI Playgrounds & Suggestion",
            TextKey.SECTION_NEARBY to "Live Activities Nearby",
            TextKey.SETTINGS_TITLE to "Preferences & Settings",
            TextKey.SETTINGS_LANG to "App Language",
            TextKey.SETTINGS_THEME to "Visual Atmosphere",
            TextKey.SETTINGS_NOTIFICATIONS to "Activity Intent Alerts",
            TextKey.SETTINGS_PRIVACY to "Incognito Intent Guard",
            TextKey.SETTINGS_ACCOUNT to "Safety & Moderation Verification",
            TextKey.SETTINGS_SAVE to "Save Preferences",
            TextKey.PROFILE_TITLE to "My Hub Profile",
            TextKey.PROFILE_BIO to "A brief summer description or preference notes...",
            TextKey.PROFILE_EDIT to "Edit Bio",
            TextKey.PROFILE_VERIFIED to "Trust Status: Verified Safety Core",
            TextKey.PROFILE_PREFS to "Active Preferences",
            TextKey.ASSISTANT_TITLE to "Meetly Assistant",
            TextKey.ASSISTANT_PLACEHOLDER to "Ask Gemini: 'I'm bored and have $10, what can I do nearby?'",
            TextKey.GROUP_JOIN to "Join Intention Hub",
            TextKey.GROUP_LEAVE to "Exit Intention Hub",
            TextKey.GROUP_CHAT to "Ephemeral Activity Chat",
            TextKey.GROUP_MEMBERS to "Intent Holders",
            TextKey.GROUP_MEETING to "Coordinated Venue Coordinates",
            TextKey.WEATHER_HOT_ALERT to "☀️ Hot outside! Recommended: indoor board games, ice skating, or seaside picnics.",
            TextKey.WEATHER_RAIN_ALERT to "🌧️ Rain alert! Nearby users switched to indoor tables, volleyball arenas, or board game cafes.",
            TextKey.WEATHER_GOOD_ALERT to "🍃 Excellent gentle weather. Perfect time for outdoor walks, cycling, or outdoor beach volleyball!",
            TextKey.SAFETY_REPORT to "Report Active Group / Moderate",
            TextKey.SAFETY_REPORT_SUBMITTED to "Report securely registered. Meetly Trust moderators will inspect items in 15 minutes.",
            TextKey.INTENT_PROMPT_LABEL to "Tell us your primary real-life intent:",
            TextKey.DISCOVER_MATCHES_TITLE to "Matches Tailored to Your Intent",
            TextKey.GO_BACK to "Go Back",
            TextKey.NAV_HOME to "Discover",
            TextKey.NAV_ASSISTANT to "Gemini Chat",
            TextKey.NAV_PROFILE to "My Profile",
            TextKey.NAV_SETTINGS to "Settings",
            TextKey.NAV_MAP to "Map",
            TextKey.BUDGET_FREE to "Free",
            TextKey.BUDGET_CHEAP to "Budget Friendly",
            TextKey.BUDGET_MEDIUM to "Moderate",
            TextKey.BUDGET_EXPENSIVE to "Premium / High End",
            TextKey.TIME_NOW to "Right Now (1-2hr)",
            TextKey.TIME_TODAY to "Later Today",
            TextKey.TIME_TONIGHT to "Tonight",
            TextKey.TIME_WEEKEND to "This Weekend",
            TextKey.CATEGORY_SPORTS to "Sports Activities",
            TextKey.CATEGORY_GAMES to "Board Games & Cafe",
            TextKey.CATEGORY_OUTDOORS to "Outdoors & Hiking",
            TextKey.CATEGORY_SOCIAL to "Social Activities & Walks",
            TextKey.CATEGORY_MUSIC to "Music jams & concerts"
        ),
        AppLanguage.RU to mapOf(
            TextKey.APP_NAME to "Meetly",
            TextKey.TAGLINE to "Встречайтесь. Действуйте.",
            TextKey.SPLASH_SUBTITLE to "Google Поиск для реальных активностей",
            TextKey.GET_STARTED to "Начать работу",
            TextKey.ONBOARDING_TITLE_1 to "Намерение во главе",
            TextKey.ONBOARDING_DESC_1 to "Никакого бесконечного скроллинга профилей. Просто напишите, чем хотите заняться, и Meetly мгновенно найдет единомышленников.",
            TextKey.ONBOARDING_TITLE_2 to "Умная AI Группировка",
            TextKey.ONBOARDING_DESC_2 to "Наш ИИ-движок сопоставляет схожие намерения, предлагает точки встречи, время и создает временные чаты.",
            TextKey.ONBOARDING_TITLE_3 to "От планов к действию",
            TextKey.ONBOARDING_DESC_3 to "Футбол, волейбол, прогулки на природе, пикники или настольные игры. Воплощайте планы в жизнь прямо сейчас.",
            TextKey.NEXT to "Далее",
            TextKey.SKIP to "Пропустить",
            TextKey.AUTH_TITLE to "Присоединяйтесь к Meetly",
            TextKey.AUTH_SUBTITLE to "Найдите свою атмосферу и компанию для любого дела.",
            TextKey.AUTH_GOOGLE_BTN to "Продолжить через Google",
            TextKey.AUTH_AGREE to "Продолжая, вы соглашаетесь с нашими стандартами безопасности и модерации.",
            TextKey.SEARCH_PLACEHOLDER to "Чем вы хотите заняться прямо сейчас? (например, 'волейбол')",
            TextKey.SECTION_RECOMMENDATIONS to "Рекомендации искусственного интеллекта",
            TextKey.SECTION_NEARBY to "Активности поблизости",
            TextKey.SETTINGS_TITLE to "Настройки приложения",
            TextKey.SETTINGS_LANG to "Язык приложения",
            TextKey.SETTINGS_THEME to "Визуальная тема",
            TextKey.SETTINGS_NOTIFICATIONS to "Оповещения об активностях",
            TextKey.SETTINGS_PRIVACY to "Режим инкогнито",
            TextKey.SETTINGS_ACCOUNT to "Верификация аккаунта",
            TextKey.SETTINGS_SAVE to "Сохранить настройки",
            TextKey.PROFILE_TITLE to "Мой профиль",
            TextKey.PROFILE_BIO to "Краткое описание вашей летней активности...",
            TextKey.PROFILE_EDIT to "Редактировать био",
            TextKey.PROFILE_VERIFIED to "Статус: Проверенный аккаунт",
            TextKey.PROFILE_PREFS to "Активные предпочтения",
            TextKey.ASSISTANT_TITLE to "Помощник Gemini",
            TextKey.ASSISTANT_PLACEHOLDER to "Спросите Gemini: 'Мне скучно, есть $10, чем заняться поблизости?'",
            TextKey.GROUP_JOIN to "Присоединиться к группе",
            TextKey.GROUP_LEAVE to "Выйти из группы",
            TextKey.GROUP_CHAT to "Временный чат активности",
            TextKey.GROUP_MEMBERS to "Участники намерения",
            TextKey.GROUP_MEETING to "Место и координаты встречи",
            TextKey.WEATHER_HOT_ALERT to "☀️ На улице жарко! Рекомендуем: настольные крытые игры, каток или пикники в тени.",
            TextKey.WEATHER_RAIN_ALERT to "🌧️ Ожидается дождь. Пользователи поблизости переходят в закрытые волейбольные клубы или кафе настольных игр.",
            TextKey.WEATHER_GOOD_ALERT to "🍃 Замечательная погода. Лучшее время для уличной прогулки, велопоездки или волейбола!",
            TextKey.SAFETY_REPORT to "Пожаловаться на группу / Модерировать",
            TextKey.SAFETY_REPORT_SUBMITTED to "Жалоба отправлена. Модераторы Meetly рассмотрят группу в течение 15 минут.",
            TextKey.INTENT_PROMPT_LABEL to "Какое ваше главное намерение прямо сейчас?",
            TextKey.DISCOVER_MATCHES_TITLE to "Подходящие группы для вас",
            TextKey.GO_BACK to "Назад",
            TextKey.NAV_HOME to "Рекомендации",
            TextKey.NAV_ASSISTANT to "Gemini Ассистент",
            TextKey.NAV_PROFILE to "Профиль",
            TextKey.NAV_SETTINGS to "Настройки",
            TextKey.NAV_MAP to "Карта",
            TextKey.BUDGET_FREE to "Бесплатно",
            TextKey.BUDGET_CHEAP to "Недорого",
            TextKey.BUDGET_MEDIUM to "Умеренно",
            TextKey.BUDGET_EXPENSIVE to "Премиум класс",
            TextKey.TIME_NOW to "Прямо сейчас (1-2 часа)",
            TextKey.TIME_TODAY to "Позже сегодня",
            TextKey.TIME_TONIGHT to "Вечером",
            TextKey.TIME_WEEKEND to "В эти выходные",
            TextKey.CATEGORY_SPORTS to "Спортивные игры",
            TextKey.CATEGORY_GAMES to "Настольные игры",
            TextKey.CATEGORY_OUTDOORS to "Походы и природа",
            TextKey.CATEGORY_SOCIAL to "Прогулки и общение",
            TextKey.CATEGORY_MUSIC to "Музыкальные встречи"
        ),
        AppLanguage.KY to mapOf(
            TextKey.APP_NAME to "Meetly",
            TextKey.TAGLINE to "Жолугуңуз. Киришүүңүз.",
            TextKey.SPLASH_SUBTITLE to "Чыныгы жашоодогу иш-чаралар үчүн Google Издөө сыяктуу",
            TextKey.GET_STARTED to "Баштоо",
            TextKey.ONBOARDING_TITLE_1 to "Биринчи кезектеги ниет",
            TextKey.ONBOARDING_DESC_1 to "Профилдерди чексиз барактап убакыт коротпоңуз. Жөн гана эмне кылгыңыз келгенин жазыңыз, Meetly сиздин адамдарды тез эле табат.",
            TextKey.ONBOARDING_TITLE_2 to "Акылдуу ИИ Топтоштуруу",
            TextKey.ONBOARDING_DESC_2 to "Биздин ИИ кыймылдаткычыбыз окшош ниеттерди бириктирет, жерлерди белгилейт, убакытты сунуштайт жана убактылуу чаттарды түзөт.",
            TextKey.ONBOARDING_TITLE_3 to "Планды ишке ашыруу",
            TextKey.ONBOARDING_DESC_3 to "Футбол, волейбол, жаратылышка чыгуу, пикниктер же стол үстүндөгү оюндар. Планды дароо чыныгы жашоодогу нерсеге айлантыңыз.",
            TextKey.NEXT to "Кийинки",
            TextKey.SKIP to "Калып калтыруу",
            TextKey.AUTH_TITLE to "Meetly'ге кошулуңуз",
            TextKey.AUTH_SUBTITLE to "Өзүңүздүн толкунуңузду табыңыз жана каалаган ишиңиз үчүн компания табыңыз.",
            TextKey.AUTH_GOOGLE_BTN to "Google менен улантуу",
            TextKey.AUTH_AGREE to "Улантуу менен сиз биздин коопсуздук жана модерация стандарттарыбызга макул болосуз.",
            TextKey.SEARCH_PLACEHOLDER to "Азыр эмне кылгыңыз келип жатат? (мис., 'волейбол')",
            TextKey.SECTION_RECOMMENDATIONS to "Жасалма Интеллект Сунуштары",
            TextKey.SECTION_NEARBY to "Жакын жердеги иш-чаралар",
            TextKey.SETTINGS_TITLE to "Тиркеменин ырастоолору",
            TextKey.SETTINGS_LANG to "Тиркеме тили",
            TextKey.SETTINGS_THEME to "Визуалдык тема",
            TextKey.SETTINGS_NOTIFICATIONS to "Иш-чаралар жөнүндө билдирүүлөр",
            TextKey.SETTINGS_PRIVACY to "Инкогнито режими",
            TextKey.SETTINGS_ACCOUNT to "Аккаунтту текшерүү",
            TextKey.SETTINGS_SAVE to "Ырастоолорду сактоо",
            TextKey.PROFILE_TITLE to "Менин профилим",
            TextKey.PROFILE_BIO to "Жайкы кызыгууларыңыз жөнүндө кыскача маалымат...",
            TextKey.PROFILE_EDIT to "Биографияны өзгөртүү",
            TextKey.PROFILE_VERIFIED to "Статус: Текшерилген колдонуучу",
            TextKey.PROFILE_PREFS to "Активдүү тандоолор",
            TextKey.ASSISTANT_TITLE to "Gemini Жардамчысы",
            TextKey.ASSISTANT_PLACEHOLDER to "Gemini'ден сураңыз: 'Ичим пышып жатат, колумда $10 бар, жакын жерде эмне кылса болот?'",
            TextKey.GROUP_JOIN to "Топко кошулуу",
            TextKey.GROUP_LEAVE to "Топтон чыгуу",
            TextKey.GROUP_CHAT to "Убактылуу иш-чара чаты",
            TextKey.GROUP_MEMBERS to "Ниеттеш катышуучулар",
            TextKey.GROUP_MEETING to "Жолуга турган жер жана координаттар",
            TextKey.WEATHER_HOT_ALERT to "☀️ Сыртта абдан ысык! Пикник же көлөкөдө убакыт өткөрүүнү сунуштайбыз.",
            TextKey.WEATHER_RAIN_ALERT to "🌧️ Жаан жаашы күтүлүүдө. Колдонуучулар жабык спорт залдарга же оюн конок үйлөрүнө өтүп жатышат.",
            TextKey.WEATHER_GOOD_ALERT to "🍃 Жакшы сонун аба ырайы. Сыртта сейилдөө, велосипед тебүү же волейбол үчүн эң сонун убакыт!",
            TextKey.SAFETY_REPORT to "Топко каршы даттануу / Модерация",
            TextKey.SAFETY_REPORT_SUBMITTED to "Дароо катталды. Meetly модераторлору топту 15 мүнөттүн ичинде карап чыгышат.",
            TextKey.INTENT_PROMPT_LABEL to "Азыр негизги ниетиңиз кандай?",
            TextKey.DISCOVER_MATCHES_TITLE to "Сизге туура келген топтор",
            TextKey.GO_BACK to "Артка",
            TextKey.NAV_HOME to "Издөө",
            TextKey.NAV_ASSISTANT to "Gemini Маек",
            TextKey.NAV_PROFILE to "Профиль",
            TextKey.NAV_SETTINGS to "Ырастоолор",
            TextKey.NAV_MAP to "Картасы",
            TextKey.BUDGET_FREE to "Акысыз",
            TextKey.BUDGET_CHEAP to "Арзан / Ыңгайлуу",
            TextKey.BUDGET_MEDIUM to "Орточо",
            TextKey.BUDGET_EXPENSIVE to "Премиум деңгээлде",
            TextKey.TIME_NOW to "Азыр (1-2 саатта)",
            TextKey.TIME_TODAY to "Бүгүн кечирээк",
            TextKey.TIME_TONIGHT to "Бүгүн түнү",
            TextKey.TIME_WEEKEND to "Ушул дем алыш күндөрү",
            TextKey.CATEGORY_SPORTS to "Спорт оюндары",
            TextKey.CATEGORY_GAMES to "Үстөл оюндары",
            TextKey.CATEGORY_OUTDOORS to "Саякат жана жаратылыш",
            TextKey.CATEGORY_SOCIAL to "Сейилдөө жана баарлашуу",
            TextKey.CATEGORY_MUSIC to "Музыкалык жолугушуулар"
        )
    )

    fun getString(language: AppLanguage, key: TextKey): String {
        return translations[language]?.get(key) ?: translations[AppLanguage.EN]?.get(key) ?: ""
    }
}

// Composition Locals to easily fetch the active language and change it
val LocalAppLanguage = compositionLocalOf { AppLanguage.EN }
